### ISSUE TITLE
Port to GTK+ 3 is completed but not yet released

### ISSUE THREAD

**Issue by tony37** [sugarlabs/XOlympics#2]
The activity shows version 1 after port to gtk3. This is not the v1 in ASLO.

**Comment by quozl** [comment]
Yet to be done;

- [ ] release v2.

**Comment by yell0wfl4sh** [comment]
how to fix this?

**Comment by quozl** [comment]
Thanks, good question.

If you'd like to take on responsibility, here's a checklist;

- [x] contact the previous activity maintainers, see http://activities.sugarlabs.org/en-US/sugar/addon/4259 and ask them if they will make a release, give them a day or two to respond,

- [x] then work with administrators of activities.sugarlabs.org to get an account there and take over maintainer role, give them a day or two to respond,

- [ ] or for publishing via HTTP, get a shell account https://wiki.sugarlabs.org/go/Service/shell

For the steps in making a release; see [this Wiki page section](https://wiki.sugarlabs.org/go/Development_Team/Release#Fructose_.28base_activity.29_modules) which refers to our core set of activities.  Some of the steps are relevant for a non-core activity.  You can do this steps privately for yourself in preparation.

As for me, I'm not directly interested in this activity, because I don't ship it from manufacturing, so I've not taken on the responsibility of activity maintainer.

**Comment by yell0wfl4sh** [comment]
@ezequielpereira Hi!, are you willing to make a release?

**Comment by ezequielpereira** [comment]
@yashagrawal3 I do not manage this activity, I can not take the decision of making a release.
I am not sure who can take that decision.

**Comment by yell0wfl4sh** [comment]
@quozl can you add me as a maintainer at activities.sugarlabs.org, I wish to release this activity.

**Comment by quozl** [comment]
But I did.  Has it not worked?

**Comment by yell0wfl4sh** [comment]
you have added me as a contributor on github, not on activities.sugarlabs.org.

**Comment by quozl** [comment]
ah, thanks.

**Comment by quozl** [comment]
added.

(currently in the open education miniconf of linux.conf.au)

**Comment by yell0wfl4sh** [comment]
I think you have added username 'yashagrawal3' , I forgot it's password so I made a new working one 'yashagrawal'. Please excuse me for such a hassle. Please add username 'yashagrawal'.

**Comment by quozl** [comment]
There was no option to add username, I was only asked to enter an e-mail address, so I used the e-mail address on your GitHub profile.  If you registered with activities.sugarlabs.org using a different e-mail address, what was it?

**Comment by yell0wfl4sh** [comment]
Then it should have been fine. For confirmation it is yagrawal900@gmail.com .
But XOlympics doesn't appear on my developers hub, also received no email notification. Please check.

**Comment by quozl** [comment]
Well, if that hasn't worked next step is to ask others (e.g. systems@).  I've confirmed your address is shown as a developer of the activity.

**Comment by yell0wfl4sh** [comment]
It works now. Thanks a lot.

**Comment by yell0wfl4sh** [comment]
- updated version to v3
- added NEWS file
- added .xo file on activities.sugarlabs.org

In status it gives 'In Sandbox, pending review', what does that mean?

**Comment by quozl** [comment]
- [x] NEWS file is backwards; most recent should be first,

- [x] NEWS file does not have v3 details,

In Sandbox is waiting for an editor to review.  I'm an editor, so I can review.

**Comment by yell0wfl4sh** [comment]
Updated NEWS file..

**Comment by yell0wfl4sh** [comment]
@quozl please review it.

**Comment by quozl** [comment]
Thanks.
